### ISSUE TITLE
Vimeo video does not exist error

### ISSUE THREAD

**Issue by sofysha91** [fancyapps/fancybox#2144] opened 2018-12-07 18:27 UTC
Hi! I'm using fancybox in my site to display some videos from Vimeo and I'm getting the next screen 
![image](https://user-images.githubusercontent.com/16858900/49665748-6c219000-fa1b-11e8-9bff-9cff572c1b37.png)

When I open the URL for Vimeo it's working as expected
https://vimeo.com/267304090/6cab7ea2ac
I hope you can help me with this
Thanks!

**Comment by fancyapps** [comment] 2018-12-10 10:22
Duplicate of #1551

Vimeo videos are currently recognized if URL matches `vimeo.com/ID` (for example, `https://vimeo.com/191947042`) or `vimeo.com/ANYTHING/ID` (for example, `https://vimeo.com/channels/staffpicks/119293996`), but you are using an unusual URL, most likely because it is a private video. And urls like this will work when media helper will be rewritten to use oembed.

**Closed by fancyapps** 2018-12-10 10:22 UTC

**Comment by btdevdesign** [comment] 2019-04-16 23:09
Try replacing `Line 3465` of `jquery.fancybox.js`:

```
vimeo: {
      matcher : /(?:vimeo(?:pro)?.com)\/(?:[^\d]+)?(\d+)(?:.*)/,
      params: {
        autoplay: 1,
        hd: 1,
        show_title: 1,
        show_byline: 1,
        show_portrait: 0,
        fullscreen: 1
      },
      paramPlace: 3,
      type: "iframe",
      url  : '//player.vimeo.com/video/$1'
},
```

**Comment by davevsdave** [comment] 2021-04-29 02:16
Thanks @btdevdesign that did the trick.
