### ISSUE TITLE
HTML5 State Change Helper

### ISSUE THREAD

**Issue by owenhoskins** [fancyapps/fancyBox#383] opened 2012-09-18 11:20 UTC
Hello,

As we well know, since the advent of the Lightbox functionality, the biggest caveat has been a broken back button and non-existant permalinks. I've searched high and low, and have yet to find a Lightbox that comes bundled with a solution to this problem.

In the past I've tried patching Fancybox via its Callbacks with Jquery Hash Change, Jquery BBQ, or the Address Plugin, with some success but never a robust or easily reusable solution.

Now that HTML5 State Change is coming into maturation with the help of History.js, I would like to propose the beginnings of a Fancybox Helper to integrate back button and current state support.

What does everyone think about that? This Gist (https://gist.github.com/854622) strikes me as a good starting place.

best,
Owen

**Comment by prakaz** [comment] 2015-11-05 05:20
Has this helper been made public yet?

**Comment by fancyapps** [comment] 2017-02-28 11:47
Duplicate of #35

**Closed by fancyapps** 2017-02-28 11:47 UTC
