### ISSUE TITLE
Hi, fancyapps

### ISSUE THREAD

**Issue by BeCeDeR** [fancyapps/fancybox#2607] opened 2021-08-06 18:41 UTC
Hi,

You simply have to stop bubbling of the click event (https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation).

_Originally posted by @fancyapps in https://github.com/fancyapps/fancybox/issues/2606#issuecomment-894436693_

Thank you for your answer. I am a beginner, and for some reason my question is closed.

1. Could it be more detailed? Where should I change something (write)? Where is the "click event"? I am a pensioner, mastering something new for myself, and I still don’t understand some things. Excuse me.
2. Have I placed the photo evaluation block correctly in the data-caption?

**Comment by mjcampagna** [comment] 2021-08-09 03:38
Dude, no bueno opening duplicate tickets. It's one thing if you do so unwittingly, but here you're just spamming Issues for the repo. I already advised your to look up stopPropagation, which you've apparently done; that's how you fix it. If you need handholding, then you're going to have to purpose a software license for paid support. The author being overwhelmed with support requests such as this is exactly why the pricing model for the new FancyApps components are so discouraging.

**Comment by fancyapps** [comment] 2021-08-10 06:47
Duplicate of #2606

This issue tracker is for actual issues, if you have questions or need help with custom coding, please use https://stackoverflow.com/questions/tagged/fancybox

**Closed by fancyapps** 2021-08-10 06:47 UTC
