### ISSUE TITLE
Q: How to open the image in zoom mode by deafult?

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [fancyapps/fancybox#2195] opened 2019-02-06 18:42 UTC
I want to create lightbox zoom effect & auto-zoom by deafult? (Without click interaction). 

For now this trick (Add click event) - not working well:
https://codepen.io/ezra_siton/pen/VgrjKw

Q2 - related: How to create scroll up/down to zoom in/out?

**Comment by fancyapps** [comment] 2019-02-07 09:58
Duplicate of #1343

Sorry, it is not possible yet, but it will be implemented in the next major version.

**Closed by fancyapps** 2019-02-07 09:58 UTC

**Comment by Ezra-Siton-UIX** [comment] 2019-02-07 10:08
Thanks. And what about the scroll (zoom) trick?

Thier is zoom event (On "scroll" by event zoom)

**Comment by fancyapps** [comment] 2019-02-07 11:30
Well, there are `scaleToActual()` and `scaleToFit()` methods and `scaleToActual()` method accepts `x, y, duration` arguments that you can use to scale to specific poision, for example `$.fancybox.getInstance().scaleToActual(200, 200)`

**Comment by Ezra-Siton-UIX** [comment] 2019-02-07 11:55
Thier is codepen about the idea of this methods?
Where i put for example the scaleToActual()? (Only afterShow?)

**Comment by fancyapps** [comment] 2019-02-07 11:59
The idea would be to use some callback, for example, afterLoad, to bind scroll event that would eventually call these methods. Each callback receives first argument as reference to the instance, so you can easily access each instance method, see any demo from docs and you will get an idea.

**Comment by Ezra-Siton-UIX** [comment] 2019-02-07 12:06
Like this? Sorry no examples for this ideas (Full example)

Not working:
```
   afterLoad:function(instance, current) {
          $(".fancybox").scaleToActual(222, 222)
    }
```
Not working:

```
   afterLoad:function(instance, current) {
         instance.scaleToActual(222, 222)
    }
```

**Comment by fancyapps** [comment] 2019-02-07 12:11
Scaling would not work inside `afterLoad` directly, either use `afterShow` callback https://codepen.io/anon/pen/bzYJyZ?editors=1010 or disable animations - https://codepen.io/anon/pen/omoOKo?editors=1010

**Comment by Ezra-Siton-UIX** [comment] 2019-02-07 12:15
Ok. When i am writing 

`instance.scaleToActual(5, 5),
`
I dont see a lot of change.  5,5 (This is X=5, Y=5) Or 5px?

**Comment by fancyapps** [comment] 2019-02-07 12:20
Well, it is integer and is a value of distance from image top/left corner in px. You would not see big difference, because the script intelligently centers image so it does not move too far from any screen side. To see the effect, try passing 0, 0 and, for example, 1000,1000; that would be ~ the same as clicking on top/left and bottom/right corner of thumbnail.

**Comment by Ezra-Siton-UIX** [comment] 2019-02-07 12:40
More clear now - thanks.

Ok. Last - if for example i want when you open image 1 show than go to image 2 - this is the code? (Right now it goes to the last image)

```
$('[data-fancybox="images"]').fancybox({
  animationEffect: false,
  afterShow : function(instance, current) {
    // Go to next gallery item=
   // instance.next( duration );
    instance.next(100);
  }
});


```
https://codepen.io/ezra_siton/pen/MLOdvb?editors=1010

Not usefull of course.

**Comment by fancyapps** [comment] 2019-02-07 13:16
`afterShow` would be called for each image, therefore it would loop till the end of the gallery :) You could either try change it using onInit callback - https://codepen.io/anon/pen/qgVzGE?editors=1010 - or you could add your own click event for links that would start fancybox manually (using $.fancybox.open([arr], {options}, index))

**Comment by mertcanaltin** [comment] 2021-01-20 17:56
I wonder if there has been an improvement in this regard
