### ISSUE TITLE
autoStart not working without thumbs

### ISSUE THREAD

**Issue by EduardJS** [fancyapps/fancybox#1961] opened 2018-06-09 00:57 UTC
Hello!

As the title suggests, I had no luck looking through the issues here seeing if this is intended behavior or not. 

Pen here: https://codepen.io/anon/pen/yEgyvz

I have pagination with 20 images per page, as well as a button showing `slideshow all` ( with all the images urls generated somewhere in the code ) and I need it to autoStart after starting the gallery.

To my surprise, I noticed this does not work unless there are actual images inside the gallery elements.

Can someone help a friend up ?
Thanks

**Comment by fancyapps** [comment] 2018-06-19 09:34
Hi,

This issue seems to be caused by the fact that there is an issue with `data-trigger` and custom options are not applied. This will be fixed in the next update.

**Comment by EduardJS** [comment] 2018-08-28 12:59
Hello!
Just catching up on this, can you let us know where exactly to look ? We could try fixing it ourselves ...

**Comment by fancyapps** [comment] 2018-08-28 18:04
Hi,

It should be fixed with the latest update - https://codepen.io/fancyapps/pen/YOyRKR?editors=1010

**Closed by fancyapps** 2018-08-28 18:04 UTC

**Comment by EduardJS** [comment] 2018-08-28 18:06
Thanks!

I have managed to work around it by simply having jQuery trigger a click directly on the hidden gallery element :)
