### ISSUE TITLE
Caption shows over video controls

### ISSUE THREAD

**Issue by pronobis** [fancyapps/fancybox#1862] opened 2018-03-03 03:53 UTC
I'm using version 3.2.5. When a video shows, the title is overlapping the controls making it impossible to control the video. In fact, it is only a shaded (almost transparent) part of the title div that overlaps. Is there a workaround?

**Comment by joaosilva1977** [comment] 2018-03-09 13:01
I have the same problem (mobile screen only).  Some way for the height of the video set to "auto"? leaving the controls just below it, and not bottom of screen.

**Comment by joaosilva1977** [comment] 2018-03-09 19:52
I solved this problem for my case (only test for youtube iframe)
add this in css code:
@media only screen and (max-width: 40.063rem) {	
.fancybox-slide--iframe .fancybox-content {
  height: auto;
  max-height: none;
}
}
.fancybox-caption {
  padding: 10px 0 15px;
}
.fancybox-caption-wrap {
  padding: 10px 2vw 0 2vw;
}

special thanks to Jānis Skarnelis, fancybox is amazing!!!

**Comment by fancyapps** [comment] 2018-04-09 08:30
@joaosilva1977 Thanks!

I think this is duplicate of #1846

**Closed by fancyapps** 2018-04-09 08:30 UTC
