### ISSUE TITLE
Disable zooming from page

### ISSUE THREAD

**Issue by KiyoshiSaundo** [fancyapps/fancybox#1286] opened 2017-03-14 11:44 UTC
Hello, how I can disable zooming image from page?

**Comment by fancyapps** [comment] 2017-03-14 11:51
You want do disable a feature that zooms image to full size after clicking it? Sorry, there is no option for that, yet. It will be included in v3.1, I`m now trying to figure out a nice API to cover various scenarios.

**Comment by KiyoshiSaundo** [comment] 2017-03-14 12:01
Sorry, my english is bad, I talk about that (gif). It's zoom not disable?
![fancy](https://cloud.githubusercontent.com/assets/12862713/23899635/0260ca42-08c7-11e7-9240-cfbdb8a84a8f.gif)

**Comment by fancyapps** [comment] 2017-03-14 12:09
Sorry, the same is about open/close animation, please, wait for v3.1.

**Comment by KiyoshiSaundo** [comment] 2017-03-14 12:10
Thank for your answer)

**Comment by fancyapps** [comment] 2017-03-14 15:57
Duplicate of #1175

**Closed by fancyapps** 2017-03-14 15:57 UTC

**Comment by Cu8eeeR** [comment] 2017-03-14 20:00
@fancyapps - is there any milestone (planned features/TODO list) for v3.1?

**Comment by fancyapps** [comment] 2017-03-14 20:12
@Cu8eeeR Sorry, there is no public list, I just have a list of notes/ideas on my notebook. 
But I feel that I`m done with 3.0 branch and now I`ll focus on API changes/improvements.

**Comment by VadimLu** [comment] 2017-03-21 00:12
Waiting for this option too..

**Comment by VadimLu** [comment] 2017-03-21 00:25
I agree, it would be great if the image just fade in/out in the center of the page without the animation of the thumbnails, thank you for implementing this feature in v3.1..

**Comment by KiyoshiSaundo** [comment] 2017-03-21 06:20
@VadimLu maybe this will help you. I made a picture opening through the object and using $.fancybox.open (items, opts, index);

**Comment by VadimLu** [comment] 2017-03-21 12:11
@KiyoshiSaundo , This should stop the animation? do you have a link to working example to take a look at the code? Thank you!

**Comment by KiyoshiSaundo** [comment] 2017-03-22 08:09
@VadimLu https://codepen.io/KiyoshiSaundo/pen/XMExmJ

I used an array so that when you view the gallery you can immediately see all the images. Initially there are several of them on the page and are loaded with ajax. Maybe it's also help you

**Comment by fancyapps** [comment] 2017-03-22 08:40
@KiyoshiSaundo nice workaround, but I would simplify it like this:

```JS
$(document).on('click', '[data-fancybox-var]', function(e) {
	e.preventDefault();

	var links = $('[data-fancybox-var]');
	var group = [];

	$.each(links, function( key, value ) {
		group.push({
			src  : value.href,
			opts : {
				caption : value.title
			}
		});
	});

	$.fancybox.open( group, {}, links.index( this ) );
});
```

See demo - https://codepen.io/anon/pen/yMKRmO?editors=1010

**Comment by KiyoshiSaundo** [comment] 2017-03-22 09:34
@fancyapps if not all links exist on page, total count by incorrect.

Example: we have gallery with 100 items and ajax loading by 10 items. We have first 10 items, open first item and see 1/10 (http://prntscr.com/en0eo9) and close fancybox. Loading next 10 items, open first and see 1/20.

But just for disable animation your example is simplify

**Comment by VadimLu** [comment] 2017-03-22 23:30
Thank you guys, your solutions working great, this is exactly what I am looking for..
I only want to know if it's possible to implement it into this way:

```
$(document).ready(function() {
    $(".fancybox").attr('data-fancybox', 'group').fancybox({touch: false});
});
```
Thank you!

**Comment by VadimLu** [comment] 2017-03-23 22:46
@fancyapps Ok, your code is great!

Only two questions about it:

```
$(document).on('click', '[data-fancybox-var]', function(e) {
	e.preventDefault();

	var links = $('[data-fancybox-var]');
	var group = [];

	$.each(links, function( key, value ) {
		group.push({
			src  : value.href,
			opts : {
				caption : value.title
			}
		});
	});

	$.fancybox.open( group, {}, links.index( this ) );
});
```

1. How can I disable/enable group (no counter) easly?
2. How can I load mixed content in one page images/inline/iframe
