### ISSUE TITLE
Usage with slider-Pro / issue after 'fullscreen'

### ISSUE THREAD

**Issue by michas0602** [fancyapps/fancybox#2564] opened 2021-03-22 15:08 UTC
Hi, yesterday I've tried to use your Fancybox with a slider-pro 'caroussel' ([link](https://www.nachtlicht-fotografie.de/portfolio/fotografie/)).

Seems fine so far, unfortunately I have a problem when closing fullscreen/Fancyboxoverlay after scrolling quick with mousewheel through the slides -
sometimes the 'parent'/clicked original image down under is missing, so I just see my preloader-gif - and not an image anymore.
And sometimes the slides are not centered anymore inside its parent slide after fullscreen...

Not sure whats causing it, unfortunately David from Slider-Pro seems to be inactive - have you possibly an idea whats causing this or how to solve?

Many, many thanks already and with best regards, Michael

**Comment by fancyapps** [comment] 2021-03-22 15:11
Hi,

Typically, issues like this are caused by the fact that fancybox places focus back on the trigger element after closing, that can confuse carousels/sliders. You can fix that by setting `backFocus: false`

**Comment by michas0602** [comment] 2021-03-22 15:13
I'll try this later today, many thanks mate for the quick reply :) !!

**Comment by michas0602** [comment] 2021-03-23 00:42
It seems you solved both of my problems within seconds...awesome, many thanks

**Closed** 2021-03-23 00:42 UTC
