### ISSUE TITLE
hash option doesn't work as expected

### ISSUE THREAD

**Issue by ErikKrause** [fancyapps/fancybox#2141] opened 2018-12-04 18:16 UTC
I discovered that I can add an individual hash per image using `data-hash` in the call. Fancybox shows that hash value in the URL, which is nice and would provide meaningful URLs for direct linking. However, this links don't open the gallery image as is the case with the automatically created hashes.

Background: I have a page with images in several sections and between one to 10 images in each section. I don't want to open a different gallery for each section since then there are galleries that contain only one image, which might be frustrating for the user. On the other hand I want to reflect the section in the URL for deep linking.

**Comment by fancyapps** [comment] 2018-12-04 18:30
Looks like duplicate of #1407

Custom hashes are currently not supported. If you wish, you can try to implement that by yourself. e.g., check for hash and then open/close corresponding item. But be aware that this is tricky due to fact that some people expect that "clicking back button" would close current instance, too.

**Closed by fancyapps** 2018-12-04 18:30 UTC
