### ISSUE TITLE
Fancybox v3.0.47: Doesn't close when clicking outside image on Mobile

### ISSUE THREAD

**Issue by entreprenr** [fancyapps/fancybox#1334] opened 2017-03-30 17:18 UTC
On the phone: 
When I click outside the image, it toggles (show/hide) the close button, but it doesn't close fancybox.

This behaviour seems to be by design, but it is confusing to me and probably others as well.

If this is by design, could you add an option that it would instead close the image?

**Comment by fancyapps** [comment] 2017-03-30 17:20
Duplicate of #1175. This will be customizable in v3.1.

**Closed by fancyapps** 2017-03-30 17:20 UTC
