### ISSUE TITLE
After Closing Gallery it brings you to the top position of last opened image

### ISSUE THREAD

**Issue by sunnysette** [fancyapps/fancybox#1350] opened 2017-04-07 08:42 UTC
Hi guys, 

i've some issues with your script:

when i close a gallery, it brings me to the first opened image position in the page.
You can try by yourself, <a href="https://rondadesign.it/prodotti/nirvana/" rel="nofollow" target="_blank">at this link</a>.

Just scroll halfway down the page, open the first big image and close it: the script will bring you to the top position of the image.

Can you help me understanding this behavior? and maybe disable it?

Thanks

**Comment by fancyapps** [comment] 2017-04-11 07:55
This is due to bringing back focus to the last active element. You will be able to disable this feature in v3.1.

**Comment by sunnysette** [comment] 2017-04-11 08:25
Thanks you very much.
Will wait the update :D

**Comment by fancyapps** [comment] 2017-04-11 08:43
Duplicate of #1327

**Closed by fancyapps** 2017-04-11 08:43 UTC
