### ISSUE TITLE
Specify a group ID for each picture

### ISSUE THREAD

**Issue by devozanges** [fancyapps/fancybox#1522] opened 2017-07-11 07:08 UTC
I have a list of 10 photos on a page A. I want to add a link like this one ```//mywebsite.fr/mypageA#group-8``` from another page B. My problem is I don't know what is the good ID to add to the link for reach the good picture. ```website.fr/pageX#group-x```  

I see that the ids are incremented one by one but is it possible to override a little this principle?

I would like to be able to specify the ID of my image (from database) like that I could create the link of any place of my site and it will open the good picture.

**Comment by fancyapps** [comment] 2017-07-11 08:09
Hi,

Sorry, it is currently not possible to customize, hash is generated from group name and index.

Duplicate of #1407

**Closed by fancyapps** 2017-07-11 08:09 UTC
