### ISSUE TITLE
JS Error when clicking Thumbs

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancyBox#1194] opened 2017-01-20 13:06 UTC
Not entirely sure what's triggering this, but when I click enough thumbnails in the Fancybox thumbnail grid, I eventually get this error:

Uncaught TypeError: Cannot set property 'isMoved' of undefined

The error points to this line:

self.current.isMoved    = false;

I can't imagine why, though.

**Comment by fancyapps** [comment] 2017-01-20 15:20
Hmm, I tried to reproduce this, but it works ok for me. What line it is? And what jQuery version are you using? Are you using the latest fancybox code?

**Comment by mjcampagna** [comment] 2017-01-20 15:32
Latest Fancybox and jQuery. The thumbnails work okay for a time, but eventually the error occurs. I have not found any reliable way to trigger the error other than to keep clicking until it breaks.

**Comment by fancyapps** [comment] 2017-01-20 15:36
But could you tell at what js line this error occurs? if using minified version, then maybe you could figure out what method this causes.

**Comment by mjcampagna** [comment] 2017-01-20 15:50
The console is showing the error on line 752:

```javascript
self.current.isMoved = false;
```

**Comment by fancyapps** [comment] 2017-01-20 16:06
I`m trying to reproduce this, but everything works fine for me, even if I click like crazy.
But I`ll look through the source and will try to figure out what could cause this problem. I get feeling that might be connected with the issue the other guy has described in the main thread about v3.

**Comment by mjcampagna** [comment] 2017-01-20 16:26
Thanks for looking into it. If I come up with any details more concrete, I'll let you know.

**Comment by fancyapps** [comment] 2017-01-24 08:52
Please, update to the latest commit and try to reproduce this issue.

**Comment by mjcampagna** [comment] 2017-01-24 09:33
I got it to happen again. Opened the thumbnails, then clicked around quickly for a while, selecting different thumbnails. Tried a second time, waiting a longer time between clicks, and actually got it to happen after fewer clicks.

I don't know whether this is anecdotal or not, but it seems to occur frequently when clicking between distant thumbnails. By which I mean, moving between two images having many images between them in the sequence.

**Comment by fancyapps** [comment] 2017-01-24 10:07
Hmmm, what about now? 

I was not able to reproduce this even with many thumbs (btw, what do you understand by "many" - hundreds? thousands?), but I think I found a place in the code where it could potentially break.

**Comment by mjcampagna** [comment] 2017-01-24 12:26
Okay, getting weird. I've got 44 images in the collection I'm testing with. I clicked around a bit, and eventually the image just stopped changing. No error in the console log this time, though; it's just quietly stopped working. Again, seemed to occur after clicking through several images, and then jumping from an image early in the gallery to one near the end.

**Comment by mjcampagna** [comment] 2017-01-24 12:30
Just got it to happen a second time, exactly as described above. This time when it happened, I pressed "G" to close the thumbnails. The slideshow updated, and the slide was then blank. I pressed "G" again to reopen the thumbnails, then clicked another image; it worked, and the new image slid into view. I then click on thumbnails a bit again until it happened again; this time, however, I am unable to recover functionality by opening and closing the thumbnails.

**Comment by fancyapps** [comment] 2017-01-24 14:46
Now I finally got it :) All this time I was thinking this is connected with fast clicking on thumbs, but turns out, the problem is caused by opening/closing thumb grid while sliding animation has not finished. I`ll look to fix this.

**Comment by mjcampagna** [comment] 2017-01-24 14:59
Glad to be a help narrowing down problems. =D

**Comment by fancyapps** [comment] 2017-01-24 15:55
Let's hope the latest commit fixed this issue, fingers crossed :D
The content is now repositioned immediately after toggling thumbs.

**Comment by mjcampagna** [comment] 2017-01-25 02:18
So far, so good! Thanks for sticking with this one.

**Closed** 2017-01-25 08:03 UTC
