### ISSUE TITLE
V3 Idle State & Fill Style

### ISSUE THREAD

**Issue by GeorgeRT** [fancyapps/fancybox#1214] opened 2017-02-05 18:38 UTC
Jānis, are you planning on adding an "idle state" where the controls are hidden during inactivity.  I have my margins set to [0,0] to fill the window with the image:

![image](https://cloud.githubusercontent.com/assets/25399235/22628796/933ed112-eb8f-11e6-9629-60e4cbb430b8.png)

Also, an image "fill style" would be nice, eg, zoom, crop, fill, full, etc.  Thanks.

**Comment by mjcampagna** [comment] 2017-02-06 04:48
@GeorgeRT 
Here's code I'm using to hide parts of my skin on inactivity. I'm working locally, so there's nothing online that I can share, but I think this should be pretty self-explanatory. This goes into the onInit callback function.

```javascript
				/** mouse movement */
				var i, container = instance.$refs.container; container
					.on("mousemove", function() {
						clearTimeout(i);
						$(container).addClass("mouse-is-moving");
						i = setTimeout(function () {
							$(container).removeClass("mouse-is-moving");
						}, 2500);
					})
					.on("mouseleave", function() {
						clearTimeout(i);
						$(container).removeClass("mouse-is-moving");
					});
```

You can then add CSS for your UI elements, including opacity transitions, visibility states, etc. based on the .mouse-is-moving class.

**Comment by GeorgeRT** [comment] 2017-02-06 15:53
Hey thanks. I'll work with that.

**Comment by GeorgeRT** [comment] 2017-03-01 19:54
Great! Thanks.

**Comment by fancyapps** [comment] 2017-06-08 14:27
Hi,

Idle state has been implemented recently (use `idleTime` option to customize idle time or disable completely).

And your second request is probably duplicate of #1343

**Closed by fancyapps** 2017-06-08 14:27 UTC
Labels: Feature request

**Comment by GeorgeRT** [comment] 2017-06-08 15:05
Thank you!
