### ISSUE TITLE
latest bower.json is not part of the latest release (2.1.5)

### ISSUE THREAD

**Issue by benkroeger** [fancyapps/fancyBox#940] opened 2014-10-06 08:47 UTC
can you please include the changes you made  to bower.json in the latest label / release? That would help a lot with build processes a la yo webapp and also with dependency resolution

thanks!

**Comment by mikaelengstrom** [comment] 2015-06-10 08:04
+1

**Comment by fancyapps** [comment] 2017-02-28 12:38
Duplicate of #820

**Closed by fancyapps** 2017-02-28 12:38 UTC
