### ISSUE TITLE
When in Gallery View, can the hash url be a specific ID assigned to the item?

### ISSUE THREAD

**Issue by mmoser-markl** [fancyapps/fancybox#2481] opened 2020-06-26 03:00 UTC
When you are in gallery view and click on an image, the URL gets added by a hash usually defined by `data-fancybox="video"`. So in this case, the url will be example.com/#video-1 on the very first item and the example.com/#video-2 for the 2nd one. That's all good if your items aren't dynamically changing over time. If I have a new gallery item added on top, example.com/#video-1 is now a different item than before. So when you send that link to someone, they will be getting a different one. 

So if I my item has an ID, for example, **firstvid**, can the hash url be **example.com/#firstvid**? If so, how do you do that?

**Comment by fancyapps** [comment] 2020-06-30 09:24
Duplicate of #1407

**Closed by fancyapps** 2020-06-30 09:24 UTC
