### ISSUE TITLE
main property in bower.json

### ISSUE THREAD

**Issue by fr-olivier** [fancyapps/fancyBox#932] opened 2014-09-20 15:46 UTC
Hello,

When I install fancybox through Bower, the bower.json file does not have a "main" property (which should be "main": "source/jquery.fancybox.pack.js" or "main": "source/jquery.fancybox.js") to reference the main js file. I rely on this property in my build process (Gulp takes the main js files of every installed bower component installed and concatenates them), can you add it please?

Thank you,
François

**Comment by dolanmiu** [comment] 2015-02-14 02:46
Can this be re-openned? I am still having this issue...

**Comment by kartofelek007** [comment] 2015-02-27 12:29
I install fancybox by:
bower install
but then i dont have .bower.json but not bower.json in fancybox folder.

I install fancybox by:
bower install fancybox#master 
and in bower.json master files  I have both files:

"main": [
		"source/jquery.fancybox.css",
		"source/jquery.fancybox.js",
		"source/blank.gif",
		"source/fancybox_loading.gif",
		"source/fancybox_loading@2x.gif",
		"source/fancybox_overlay.png",
		"source/fancybox_sprite.png",
		"source/fancybox_sprite@2x.png",
		"source/jquery.fancybox.pack.js"
	],

**Comment by christianmagill** [comment] 2015-04-10 01:27
Correct me if I'm wrong, but I don't believe both jquery.fancybox.js and jquery.fancybox.pack.js should be included.

**Comment by kartofelek007** [comment] 2015-04-10 19:37
Yes. Only one file is required.

**Comment by fancyapps** [comment] 2017-02-28 12:38
Duplicate of #820

**Closed by fancyapps** 2017-02-28 12:38 UTC
