### ISSUE TITLE
Update current fancybox content?

### ISSUE THREAD

**Issue by seabasss** [fancyapps/fancybox#1249] opened 2017-03-01 00:19 UTC
Hey,

v3 looks awesome. Thanks!
A few questions...

1)
When I load content with ajax, how can I click on a link in it that gives me the new content in the same fancybox? Right now it opens a new fancybox on top.

2)
How can I make the fancybox take up about 80% of the height of the page and then have the content scroll inside of it, and have the close button in the corner right outside of the fancybox, not all the way up in the corner of the page. I saw a thread about something similar here but when I try to make the content scroll I have to use overflow: scroll which makes it impossible to move the close button outside of the div.

3)
How do I disable title/caption? Is there a js way instead of display: none for the caption element?

4)
If a <script> is first in the content that is loaded via ajax the whole script loads as text. A single space or some other content infront of the script tag fixes it. Any cleaner workaround for this? No big deal. // Edit // I just realized that v3 makes new slides based on the containers loaded so I assume it tries to create a slide out of the script tag. I moved the script inside the div so it's solved. Pretty cool feature btw. It might be an alternative for the close button issue above if I put only the button in it's own slide to control it's position outside of the main fancybox.

Thank you so much!

**Comment by fancyapps** [comment] 2017-03-01 12:09
Hi, Thanks for your feedback!

About first question. While I understand why you are asking this question (because that is how v2 and other script work), it actually does not make sense for v3. You see, v3 works more like a slider, when new instance is created, the script creates markup and sets content blocks side by side so user can swipe. It is not possible to reuse previously created dom elements when creating new instance.

So, I do not know what are you trying to archive, but probably you could simply switch content using tabs or something like that. If you really need, you could create your own click handler for links and update contents of current slide by yourself.  
This is how you can access slide element: `$.fancybox.getInstance().current.$slide`

It is also possible to set custom content using `setContent`, but I am not sure if this is what you are looking for:

```JS
$.fancybox.getInstance().setContent( $.fancybox.getInstance().current, 'Another content' );
```

.
.
.

2&4. You would have to use two wrapping elements. There are some CSS rules that are applied to the first one by default that makes content centered (v2 uses JS to do all calculations, but v3 uses this trick to avoid that). Take a look at this ajax example and just play with CSS - http://codepen.io/fancyapps/pen/JEoOvK

.
.
.

About caption. Are you using "title" attribute? I hesitated to drop support for it and only support "data-caption" , but now I think that I should have done that. I will change this probably for v3.1.

So, to disable caption, you have two options: using empty `data-caption=""` attribute or by JS:

```JS
$('[data-fancybox]').fancybox({
  caption: function() {
    return '';
  }
});
```

**Comment by seabasss** [comment] 2017-03-01 22:02
Great, thanks! :)

This is close to what I want! Any way to do it with built in fancybox features instead of $.get? And is there an easy way to make a nicer transition from the old content to the new instead of a hard swap?

	$(document).on('click', '.select-tabs .dark', function(e) {
		e.preventDefault();
		var target = $(this).data('src');
		$.get(target, function (data) {
			$.fancybox.getInstance().setContent( $.fancybox.getInstance().current, data );
		});
	});

Checking out the modal content right now, it looks great! Thank you!

**Comment by fancyapps** [comment] 2017-03-02 12:48
Sorry, there is no built-in functionality you could use to avoid doing that. And if there would be, it would look similar.

About transitions. You see, v3 avoids using JS to set content dimensions/position, it uses some CSS tricks instead. Therefore there are no methods for sizing/repositioning the content. You can use CSS transitions to do that, but, the problem is that CSS transitions can not animate width/height properties from "auto" to "auto" or from "auto" to, for example, 500px. So, in order to make nice CSS transition you would need to do those steps - 1) calculate width/height of content and set it using JS; 2) Loaded new content 3) Calculate width/height of the new content and set it using JS. This way you will see nice resizing animation. Of course, you would need to set CSS transition rule, too.
Now that you are asking about this, I think I`ll try to implement this into the code. I can not tell you when and if it will be into v3 or maybe v4.

There is currently no option to toggle touch depending on device. I could implement this, but I struggle to figure out a nice api for that. I was thinking recently about creating "mobile : {}" option that would contain options that are applied if mobile device is detected. What do you say about that?

**Comment by seabasss** [comment] 2017-03-02 19:20
Thanks again! Both those things would be great in future versions! I'm not using fancybox in a way that any demo shows, but there is so much potential, especially with the new slides next to each other and the modal css functionality. I used the v3 beta and all was good, but it's getting even better for what I'm doing now!

I found another reason why I had to turn of touch. I'm also using selectize and for some reason the touch made that not working very well. The select boxes are supposed to open with only one click and close when you click outside of them, but for some reason the touch setting messed that up in some cases and the only way to close a select was to click on another form element. No real need to look into, just mentioning that something in the touch functionality interfered. Can't make it work with every plugin out there so. http://selectize.github.io/selectize.js/

**Comment by fancyapps** [comment] 2017-06-08 14:01
FYI, v3.1 is now published.

**Closed by fancyapps** 2017-06-08 14:01 UTC

**Comment by leozelion** [comment] 2018-02-23 01:12
Hi! I'm using v3.2.10.
When I change content by using setContent(), the "close" button disappears. Perhaps because it is removed in jquery.fancybox.js:2051:
```
// Remove custom close button
if ( slide.$smallBtn ) {
        slide.$smallBtn.remove();
        slide.$smallBtn = null;
}
```
Please tell me how to get rid of it or how to return the button after changing the content.

**Comment by fancyapps** [comment] 2018-04-03 18:10
@leozelion Simply trigger `onReset` event on the slide element to correctly unload the content before setting new one, something like this:

```JS
var instance = $.fancybox.getInstance();

instance.current.$slide.trigger("onReset");

instance.setContent( instance.current, 'Another content' );
```

Otherwise your inline content might disappear.
