### ISSUE TITLE
Body Append Location of FancyBox Container

### ISSUE THREAD

**Issue by code-man** [fancyapps/fancybox#2006] opened 2018-07-13 20:07 UTC
Hello,

Is there any way to have FancyBox play nicer with floating footer bars? I have something similar to:

```
<body>
    <div id="mobile-menu"></div>
    <div id="page-content">
       <section>All your main page content and design...</section>
        <div id="push" style="height: 8rem;"></div>
        <div id="footer-container"></div>
    </div>
</body>
```

What the setup does, is if the content of the page isn't enough to push the footer bar to the bottom of the browser window on its own, my CSS setup pins the footer to the bottom if in view. So if the page content is shorter than the window in other words... the footer is pinned to the bottom of the viewport. Can't figure out how to stop it from jumping... it seems Fancybox increases the height of the <body> for some reason, causing the jump.

When Fancybox opens however, it pushes up the whole footer bar up to the bottom of the content - as FancyBox is appended right before the closing body tag.

This didn't happen in your original FancyBox 3 release. There must be some difference in how FancyBox is inserted, or the calculation of the window/viewport.

**Comment by acwolff** [comment] 2018-07-14 06:38
I can’t read your code!

**Comment by code-man** [comment] 2018-07-20 13:38
Ah shoot! :) 

Updated with example HTML.

**Comment by fancyapps** [comment] 2018-08-17 11:17
Most likely there is some CSS conflict. fancybox adds `fancybox-active` class to the `<body>` -

```CSS
.fancybox-active {
    height: auto;
}
```

and maybe that is causing problems for you. Seeing a live page/demo would help to identify the cause of the issue.

**Comment by fancyapps** [comment] 2018-08-29 11:00
Maybe this helps - https://fancyapps.com/fancybox/3/docs/#faq-1 (you could also try setting `hideScrollbar:false` to check if that is causing your issue).

Closing, because issues like this need to have live demo to be properly inspected.

**Closed by fancyapps** 2018-08-29 11:00 UTC
