### ISSUE TITLE
need Dynamic Slides api functionality

### ISSUE THREAD

**Issue by SlimSavernake** [fancyapps/fancybox#1761] opened 2017-12-03 12:22 UTC
for example: http://idangero.us/swiper/demos/ 
scroll to "Dynamic Slides"

**Comment by fancyapps** [comment] 2017-12-03 12:36
Duplicate of #1479

**Closed by fancyapps** 2017-12-03 12:36 UTC

**Comment by fancyapps** [comment] 2017-12-03 12:44
btw, if you just want to add new slide to the gallery, here is a sample - https://codepen.io/anon/pen/XzOPdx?editors=1010
