### ISSUE TITLE
bower.json discrepancy

### ISSUE THREAD

**Issue by andreigec** [fancyapps/fancyBox#1059] opened 2015-09-01 00:07 UTC
bower.json in bower repo is different, missing main element at the minimum.

bower.json from github:
{
    "name": "fancybox",
    "version": "2.1.5",
    "main": [
        "source/jquery.fancybox.css",
        "source/jquery.fancybox.js",
        "source/blank.gif",
        "source/fancybox_loading.gif",
        "source/fancybox_loading@2x.gif",
        "source/fancybox_overlay.png",
        "source/fancybox_sprite.png",
        "source/fancybox_sprite@2x.png",
        "source/jquery.fancybox.pack.js"
    ],
    "ignore": [
        "*_/._",
        "fancybox.jquery.json",
        "demo"
    ],
    "dependencies": {
        "jquery": ">=1.10",
        "jquery-mousewheel": "~3.1.3"
    }
}

bower.json from bower/fancybox#2.1.5
{
  "name": "fancybox",
  "homepage": "https://github.com/fancyapps/fancyBox",
  "version": "2.1.5",
  "_release": "2.1.5",
  "_resolution": {
    "type": "version",
    "tag": "v2.1.5",
    "commit": "18d171278d21ca59067aace6d52a1adeb6462219"
  },
  "_source": "git://github.com/fancyapps/fancyBox.git",
  "_target": "~2.1.5",
  "_originalSource": "fancybox"
}

**Comment by lambertsteven** [comment] 2015-09-16 17:55
+1

**Comment by Horttcore** [comment] 2015-11-27 12:45
+1

**Comment by Horttcore** [comment] 2015-11-27 12:48
Install via

```bower install fancybox#master```

**Comment by conantp** [comment] 2016-05-21 18:32
@Horttcore - thanks for the tip, that helped me out using Fancybox with Sage 8 for Wordpress. 

One issue I'm still having is that the image URLs in the CSS don't match up when I use "gulp" and "asset-builder" - I had to manually re-write them in the CSS. I think that's something that should be addressed outside of this package but other than that everything works great.

**Comment by fancyapps** [comment] 2017-02-28 12:38
Duplicate of #820

**Closed by fancyapps** 2017-02-28 12:38 UTC
