### ISSUE TITLE
Hash reverse sorting ?

### ISSUE THREAD

**Issue by MattXcz** [fancyapps/fancybox#1545] opened 2017-07-25 09:37 UTC
Hello I have images loaded from DB, but "ORDER BY ID DESC"
Is it posible to have CustomHash set so my last first image get last id.... and last image on page will have ID(hash) 1:
```
        $('[data-fancybox="GAL"]').fancybox({
         thumbs : false,
         hash : customHash,
         touch : {
           vertical : true,  // Allow to drag content vertically
           momentum : true   // Continuous movement when panning
         },
        })
```
And 

`<a href="'.$FILE.'" data-fancybox="GAL" data-customHash='.$ID.'data-caption="'.$CAPTION.'">';`

**Comment by fancyapps** [comment] 2017-07-27 06:34
Hi, 

There is currently no option to customize the logic of how hash is handled, but you can create your own plugin, simply use existing one as a template.

Duplicate of #1407

**Closed by fancyapps** 2017-07-27 06:34 UTC
