### ISSUE TITLE
v3.1 not available via NPM

### ISSUE THREAD

**Issue by stat1x** [fancyapps/fancybox#1581] opened 2017-08-15 10:45 UTC
If I do `npm install @fancyapps/fancybox --save` to get the 3.1 version via NPM I cannot require the module like in version 3.0 with `require('@fancyapps/fancybox')($)`. I get the following error : `TypeError: t is not a function`

**Comment by fancyapps** [comment] 2017-08-15 11:45
Hi, Sorry, I am closing this issue, because I can not reproduce this and I have no clue what could be fixed/improved. If you have any suggestions, please let me know.

And, since this package has "3,272 downloads in the last month", I wonder if this works fine for others.

**Closed by fancyapps** 2017-08-15 11:45 UTC

**Comment by stat1x** [comment] 2017-08-15 12:44
Yes sorry the way I included jQuery was not correct.
Thanks!

**Comment by fancyapps** [comment] 2017-08-15 12:45
I am glad that you managed to sort it out. Could you, please, post your solution?
