### ISSUE TITLE
FancyBox-3 and tall images with scroll

### ISSUE THREAD

**Issue by Siton-Systems** [fancyapps/fancybox#1549] opened 2017-07-26 22:49 UTC
I work on **web design** - so I need to upload tall images (screenshots of web designs I made). Thier is some way to make the lightbox with scroll? (I **dont** want the design to **fit** to the viewport)

`<div class="fancybox-image-wrap" style="transform: translate(902px, 44px); width: 116px; height: 267px;">`

**I made codepen (The layout is broken but look at the idea):**
https://codepen.io/ezra_siton/pen/LjVzLR

**References:**
- https://www.behance.net/gallery/54979335/Montreal-Espace-Pour-La-Vie-cards
- (Click on the "screenshot" btn) - https://themeforest.net/item/gymful-one-and-multipage-gym-yoga-fitness-psd-template-with-shop/20308638?s_rank=1
- https://designmodo.com/startup/#components-projects

**Or even like ths fancyBox iFrame look:**
https://codepen.io/fancyapps/pen/LLPYXg?editors=1100

**Comment by fancyapps** [comment] 2017-07-27 06:16
Hi, Thanks for your insights!

Duplicate of #1343

**Closed by fancyapps** 2017-07-27 06:16 UTC
