### ISSUE TITLE
Bower issue

### ISSUE THREAD

**Issue by rctneil** [fancyapps/fancyBox#979] opened 2014-12-20 15:21 UTC
When I try to install Fancybox using Bower I don;t get the updated bower.json file. Bower also outputs these errors when doing so:

bower fancybox#\*          invalid-meta fancybox is missing "main" entry in bower.json
bower fancybox#\*          invalid-meta fancybox is missing "ignore" entry in bower.json

Any ideas on how to solve this?

**Comment by alerosa** [comment] 2015-01-12 14:46
Try to install it with the following command:
```
bower install fancybox#master
```

**Comment by nickmeagher** [comment] 2015-05-15 02:03
@alerosa that helped me!

Thanks!

**Comment by fancyapps** [comment] 2017-02-28 12:38
Duplicate of #820

**Closed by fancyapps** 2017-02-28 12:38 UTC
