### ISSUE TITLE
Wrong image size if use defaults transitionEffect

### ISSUE THREAD

**Issue by andryshok** [fancyapps/fancybox#1573] opened 2017-08-09 23:28 UTC
One window open in fancybox via ajax, after in then - clickable image open in fancybox. If use default transitionEffect fancybox image size are wrong, please see screenshot and fix it

![25](https://user-images.githubusercontent.com/10627665/29147978-33893ca0-7d73-11e7-9c95-c432733852a0.jpg)

**Comment by fancyapps** [comment] 2017-08-10 06:23
Duplicate of #1504  

Update jQuery to the latest.

**Closed by fancyapps** 2017-08-10 06:23 UTC
