### ISSUE TITLE
Bug pdf on ios

### ISSUE THREAD

**Issue by Ricco-S** [fancyapps/fancybox#1682] opened 2017-10-12 18:22 UTC
Is there a bug fix for open pdf embedder on ios ?
On my ipad mini there is a bug on opened pdf embed.
Can not scroll in dokument and pdf reader is not realy opend.

**Comment by fancyapps** [comment] 2017-10-12 18:55
Duplicate of https://github.com/fancyapps/fancybox/issues?utf8=%E2%9C%93&q=pdf%20ios

**Closed by fancyapps** 2017-10-12 18:55 UTC
