### ISSUE TITLE
Autoplay fails

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancybox#1382] opened 2017-04-19 17:22 UTC
I think we've found a hitch in the autoplay. If you move a gallery to the last image, then arrow-key back to the first image, pressing the "Play" button seems not to work. I'm not logging any errors; the slideshow just doesn't go.

**Comment by fancyapps** [comment] 2017-04-19 17:36
Hi,

If your gallery does not loop and you are on the last element then slideshow would not start. Otherwise it should. I played a bit and could not reproduce an issue. Could you maybe record a screencast or something like that? Can you reproduce this on demos from homepage or copeden?

**Comment by mjcampagna** [comment] 2017-04-19 22:41
One of my testers setup this gallery to show the problem.
http://pangolin.danielleu.com/galleries/myanmar/index.php

The problem seems to happen intermittently. Sometimes it works as expected. Sometimes not. The best way to observe it is to browse to the last image in the set, then use the arrow keys to navigate back to the first image. Then press Play. If you don't see it on the first attempt, try it a few times.

**Comment by fancyapps** [comment] 2017-04-20 06:18
@mjcampagna yes, sorry, there is an issue if you navigate really fast. The good news is that this seems to be fixed in my development version, but the bad news are - 1) I can not tell you when v3.1 will be published and 2) there will be changes related to API and layout/CSS and you will have to update your custom code.

**Comment by mjcampagna** [comment] 2017-04-20 17:38
I see. Glad the problem is identified then, and updating custom code shouldn't be too much a problem for me. Do you reckon 3.1 is a long wait away, or coming soon-ish?

**Comment by fancyapps** [comment] 2017-04-21 14:52
@mjcampagna The script is at the phase where it is cleaned, tweaked and thoroughly tested. But it seems to be quite stable already and you can preview it here - https://codepen.io/fancyapps/full/LyNXqr/

Next week I`ll start working on documentation and I will try to make it better - I`ll add more description and examples for each option. I will publish the code afterwards,

**Comment by mjcampagna** [comment] 2017-04-21 16:39
Looks good. I like the transition options! I'll be looking forward to this. =D

**Comment by fancyapps** [comment] 2017-06-08 12:45
FYI, v3.1 has been published and it should contain the fix.

**Closed by fancyapps** 2017-06-08 12:45 UTC
