### ISSUE TITLE
Maximum call stack size exceeded in beforeShow

### ISSUE THREAD

**Issue by swasical** [fancyapps/fancyBox#915] opened 2014-08-27 20:06 UTC
In version 2.1.5, there is an undefined variable in beforeShow that always evaluates to false.
if (this.fixPosition !== false) {

It then calls $("*"), which throws the error "Maximum call stack size exceeded" if there are a large number of elements on the page.

Minimum, the undefined variable should be replaced with something configurable. (I set this condition to always be false to fix this issue in my own code.) Additionally, a better algorithm should be used in place of the call to $("*") for those who need that logic to run.

**Comment by damodaran** [comment] 2016-04-20 07:37
Hi is there any updates on this issue? I am also facing the same issue in Google chrome. I am not sure the issue is related to fancybox or jquery itself. Please refer the attached image. 
![selection_182](https://cloud.githubusercontent.com/assets/1776773/14666705/b5b80f00-06f8-11e6-96cd-794e32b063e4.png)

I tried to set the above mentioned crack but it not worked for me.

**Comment by zmwangx** [comment] 2016-12-30 01:16
I ran into this problem with v2.1.5 just now, but it has been fixed in f238ea1295df7e3f6c1e0a1b48d272bf7d8ced16.

**Comment by fancyapps** [comment] 2017-02-28 07:40
Hi, please, upgrade to v3.

**Closed by fancyapps** 2017-02-28 07:40 UTC
