### ISSUE TITLE
Fancybox3 is throwing 'too much recursion' error

### ISSUE THREAD

**Issue by samuelj90** [fancyapps/fancybox#1288] opened 2017-03-14 13:16 UTC
Hi 
The detailed steps to reproduce this issue is available in following link :- 
http://stackoverflow.com/questions/42786668/fancybox-3-and-bootstrap-3-modal-oddly-bug
👍  to  the user this link has a working demo which will show the issue.
Regards
Samuel

**Comment by fancyapps** [comment] 2017-03-14 13:19
Hi,

I think this is duplicate of #1270

**Closed by fancyapps** 2017-03-14 13:19 UTC

**Comment by samuelj90** [comment] 2017-03-14 13:28
@fancyapps anyway this issue is still there right how can i resolve the issue without changing the fancybox libraray.?

**Comment by fancyapps** [comment] 2017-03-14 13:32
Sorry, I do not think there is anything you could do, except commenting out code aroud "focusin" event.
I`m in the middle of something else and I`ll take a look at this afterwards.

**Comment by AndrewLrrr** [comment] 2017-03-14 13:48
Yeah. This issue is very uncomfortable. I think that not only me hiding the gallery into modal window. And I've tried different options but none of them helped.

**Comment by fancyapps** [comment] 2017-03-14 13:51
Another solution would be just not to use bootstrap modal. You can use fancyBox to open modal and if it contains gallery links, clicking then will open a new fancyBox instance without closing prevuously opened. See "Ajax request" example on the homepage - http://fancyapps.com/fancybox/3/#ajax

**Comment by fancyapps** [comment] 2017-03-21 08:52
FYI, I fixed this in my local development copy, so, wait for the next commit.

**Comment by RoyalKnight** [comment] 2017-05-18 17:47
@fancyapps when will you push above mentioned fix and release a new version?

**Comment by fancyapps** [comment] 2017-05-18 18:17
Hi, You can get latest code here - https://github.com/fancyapps/fancybox/tree/3.1

**Comment by RoyalKnight** [comment] 2017-05-18 18:18
Thank you for the hint! I'll try it.

**Comment by cbichis** [comment] 2018-02-09 10:06
Hi,

Is this fixed ? Still getting the issue with fancyBox v3.2.10.

**Comment by fancyapps** [comment] 2018-02-09 10:09
@cbichis If you are still experiencing this, then try setting `trapFocus:false`, because both scripts try to prevent "stealing" focus from self.
