### ISSUE TITLE
Provide SCSS

### ISSUE THREAD

**Issue by ankitpinl** [fancyapps/fancybox#1944] opened 2018-05-24 13:00 UTC
Please provide .SCSS file so we can give the direct path from node_modules. Some frameworks do not support .css path so We have to put the whole CSS file in my style.css and whenever fancybox update, my fancybox.js file is updated but style does not update because of I have put it manually. I have to update the CSS file manually. So please if you could update SCSS file, it would be better for other frameworks.

**Comment by fancyapps** [comment] 2018-05-28 10:59
Duplicate of #1372

**Closed by fancyapps** 2018-05-28 10:59 UTC

**Comment by NgatiaFrankline** [comment] 2019-02-25 23:07
Having the same problem
