### ISSUE TITLE
[RESOLVED] : Adding background image or full bleed images

### ISSUE THREAD

**Issue by amyth91** [fancyapps/fancybox#1357] opened 2017-04-10 22:13 UTC
#227 

Is there a way of making the images full bleed, despite the actual image dimensions.

Currently the images are scaled down to fit the parent, but I am trying to get the image to be full bleed, something like "background-size:cover"

Thanks

**Comment by amyth91** [comment] 2017-04-10 23:52
#1357 Found a solution.

Doing this will make the container 100% : http://jsfiddle.net/RyTcS/embedded/result/

But: .fancybox-placeholder will be set to display none and image will be it's normal size.

Add this extra css to make it full bleed.

```
.fancybox-placeholder {
    display: block !important;
    position: relative;
    height: 100%;
}


  .fancybox-placeholder  img {
        object-fit: cover;
    }
```
** object-fit:cover is the answer, this makes the images behave the same way as background-size:cover
** See usage and compatibility: http://caniuse.com/#search=object-fit

**Comment by fancyapps** [comment] 2017-04-11 07:13
You can trick the script to show images as html content:

```JS
$(document).on('beforeLoad.fb', function( e, instance, current ) {
    current.type = 'html';
    current.content = '<div class="fancybox-image" style="background-image:url(' + current.src + '); background-size: cover; background-position:50% 50%;background-repeat:no-repeat;height:100%;width:100%;" /></div>';
});
```

See demo - http://codepen.io/fancyapps/pen/NjKxpQ

Maybe some day this will be included in the core.

Duplicate of #227

**Closed by fancyapps** 2017-04-11 07:13 UTC

**Comment by Cu8eeeR** [comment] 2017-04-13 19:07
It would be really nice to have it in 3.1 - blurred images are not cool
