### ISSUE TITLE
On click close button, check validate function if true then allow to close.

### ISSUE THREAD

**Issue by akifnadeem** [fancyapps/fancyBox#1061] opened 2015-09-18 12:26 UTC
Hy, i've an issue regarding validation in my program. On click close button of popup i'm using beforeClose: function(), yes it is calling my validation function and showing alert message on error but it also closing popup. I want to stop popup there and don't allow to close if there is an error or return false.

**Comment by fancyapps** [comment] 2017-02-28 11:53
Duplicate of #637

**Closed by fancyapps** 2017-02-28 11:53 UTC
