### ISSUE TITLE
Wrong behavior

### ISSUE THREAD

**Issue by usb248** [fancyapps/fancybox#1771] opened 2017-12-08 14:15 UTC
Hi,

  I use fancybox, when I open a fancybox with a content which overflow my page (so, with a scrollbar), naturally i need to scroll my fancybox in order to view all content.

BUT, problem... On touch device (in my case, windows 10 surface pro) **i can't scroll my page** when i swipe my finder (vertically) on my screen (with a 'touchstart' event on an image in my fancybox).

I investigate in the source code of the plugin. I found the code block involved. can you fix that?

Block code : [line 3528](https://github.com/fancyapps/fancybox/blob/master/dist/jquery.fancybox.js#L3528-L3531)

I commented this block while waiting. 
```
if ( $target.is('img') ) {
	e.preventDefault();
}
```
it corrects my problem...but i think it's not a good solution

Certainly related to the problem encountered in this [issue](https://github.com/fancyapps/fancybox/issues/1597).

**Comment by fancyapps** [comment] 2017-12-08 15:06
Thanks for reporting! This is not related to Windows 10 but rather to that code you mentioned.

**Comment by usb248** [comment] 2018-01-15 08:59
Any fix ?

**Comment by 7iomka** [comment] 2018-03-21 05:22
The problem is actually very rough, and it extends not only to Windows-10, but also to all touch-devices (android / ios)
Any picture inside the content of the modal window is a stumbling block - if the user tries to push off from it to scroll down the content, it can not be done! And this is for strictly images!
My workaround: 
`
.fancybox-slide--inline img { pointer-events: none; }
`
My workaround looks very rude, and I do not understand why the code in the new version has not yet fixed this hard bug?

**Comment by fancyapps** [comment] 2018-04-03 17:39
This should be fixed in the last commit.

**Closed by fancyapps** 2018-04-03 17:39 UTC
