### ISSUE TITLE
Not using fancybox -> problem opening links

### ISSUE THREAD

**Issue by Ypanesa** [fancyapps/fancybox#2201] opened 2019-02-14 10:45 UTC
**Describe the bug**
WP Website. I do not have fancybox installed. Cannot open normal links. They get additional code somehow. Cannot create new post or page with links. Happens to all newly created links and even with all plugins deactivated.

Please don't close the issue like this. It's not been solved and I'm in contact with other helpers in the WP forum. They have no clue either. 

I cannot use my website unless I find the solution.

**To Reproduce**
    1. Go to http://ffp.gifwelt.info/
    2. Click on any link
    3. See error. The link wants to open in lightbox

**Expected behavior**
Open new URL

**Screenshots**
No

**Desktop (please complete the following information):**
    * OS: Windows 10
    * Browser Firefox
    * Version 65.0.1
      Also tested with Chrome

**Comment by fancyapps** [comment] 2019-02-14 10:46
Duplicate of #2200

**Closed by fancyapps** 2019-02-14 10:46 UTC
