### ISSUE TITLE
Touch/swipe inline element

### ISSUE THREAD

**Issue by ShortSnow** [fancyapps/fancybox#1860] opened 2018-02-28 15:28 UTC
Hello,

i would like to group inline elements. That works good. With arrows on desktop i can switch and swipe with the mouse.

Mobile is touch/swipe not possible. With images there is no problem. Is there any solution? I think i have missed a class or setting.

Thanks a lot

ShortSnow

**Comment by fancyapps** [comment] 2018-03-12 08:16
Duplicate of #1528

**Closed by fancyapps** 2018-03-12 08:16 UTC
