### ISSUE TITLE
Bizarre behavior min.js version

### ISSUE THREAD

**Issue by marc-parillo** [fancyapps/fancybox#1931] opened 2018-05-09 14:13 UTC
Using Fancybox V3.  

When I include `fancybox.min.js` in my build file, fancybox opens automatically whenever any button with a data attribute is clicked.  However, when I include the unminified `fancybox.js` file, this does not happen.   Might not be a bug with FancyBox.   Just mentioning it in case anyone has run into this behavior before.

**Comment by fancyapps** [comment] 2018-05-09 16:04
I am closing this, because I have no idea how to reproduce this.

**Closed by fancyapps** 2018-05-09 16:04 UTC
