### ISSUE TITLE
This component doesn't define main assets in bower.json.

### ISSUE THREAD

**Issue by malina** [fancyapps/fancyBox#1018] opened 2015-04-10 03:44 UTC
When use https://rails-assets.org/ for rails app, i see message:
"This component doesn't define main assets in bower.json.
Please open new pull request in component's repository:
https://github.com/fancyapps/fancyBox"

**Comment by fancyapps** [comment] 2017-02-28 14:17
Duplicate of #820

**Closed by fancyapps** 2017-02-28 14:17 UTC
