### ISSUE TITLE
reducing inital image width/add margins

### ISSUE THREAD

**Issue by mikemania** [fancyapps/fancybox#2089] opened 2018-10-03 20:20 UTC
I'm using the gallery in a portrait viewport, so images are more often than not expanded 100% to the left and right. I want to add some margin and essentially zoom the image out slightly for design reasons.

Changing and reducing the width of .fancybox-stage seems to solve the problem. However, when zooming into the image, _now_ I want to have the stage be 100% in width. Instead, the zoomed in image is cutoff on the sides because obviously I reduced the stage. Very picky, I know.

Is this possible?

**Comment by fancyapps** [comment] 2018-10-04 06:45
Hi,

Sorry, v3 is not optimized for that, but this feature is planned to be introduced in the next version. E.g., there will be option to choose how to fit the image on start (fit, cover, ...).

This is actually duplicate of #1343

**Closed by fancyapps** 2018-10-04 06:45 UTC
