### ISSUE TITLE
Vanilla JavaScript

### ISSUE THREAD

**Issue by ionurboz** [fancyapps/fancybox#2426] opened 2020-02-22 21:51 UTC
Fancyapps / fancybox should now get rid of a nonsense library like jQuery and declare independence with vanilla JavaScript.

I also need this very much :/

**Comment by mjcampagna** [comment] 2020-02-24 18:49
Yeah, that will be Fancybox 4, and he's been working on it for a long while now. Be patient.

**Comment by mjcampagna** [comment] 2020-02-24 18:52
And while jQuery may not be as necessary as it once was, and has fallen out of fashion, it certainly isn't nonsense. Might be you're too young to appreciate its importance, but it has been integral to the development of JavaScript and web-development. We may not need or want to use it any longer, but it's a landmark library deserving a pedestal in the halls of JavaScript.

**Comment by ionurboz** [comment] 2020-02-24 23:34
jQuery is of course not to be underestimated. I just did a metaphor, man :)

**Comment by fancyapps** [comment] 2020-02-25 17:20
Duplicate of #1346

**Closed by fancyapps** 2020-02-25 17:20 UTC

**Comment by xitude** [comment] 2021-10-02 20:05
Have we had any further progress on this?

**Comment by fancyapps** [comment] 2021-10-03 15:29
@xitude Sure, see https://fancyapps.com/docs/ui/fancybox/
