### ISSUE TITLE
Scroll issue chrome Android (mobile)

### ISSUE THREAD

**Issue by botervet** [fancyapps/fancybox#2207] opened 2019-02-27 10:40 UTC
Hi,

I'm using FancyApp V3 end run into an issue.

When I open the lightbox on a mobile phone that uses Android it seems impossible to scroll if the content is more then 100% height.  When trying to scroll the lightbox even closes. 

How can I prevent this and be able to scroll down?!

**To Reproduce**
1. Go to http://development.botervet.nl/mysteryland/lineup/ on mobile Android device.
2. Click on Dimitri Vegas & Like Mike
3. Scroll down

**Expected behavior**
Beeing able to scroll and see the rest of the content, like on iOS

**Smartphone (please complete the following information):**
 - Device: All Android devices
 - OS: Android 9
 - Browser Chrome
 - Version Latest

![android-screenshot](https://user-images.githubusercontent.com/22473875/53484469-345b3f00-3a84-11e9-9b6c-12c7c1bd11c1.jpg)

**Comment by fancyapps** [comment] 2019-02-27 10:43
Hi,

Try setting `touch:false` (or `$.fancybox.defaults.touch = false;`) to disable touch events.

Scrolling and mobile devices is generally not good idea due to limitations of mobile browsers.

**Comment by botervet** [comment] 2019-02-27 10:58
Thanks for the quick reply! :)

I know, but this is what the client wants! :(
Tried `touch:false`, and it does work.

but the behaviour I'm looking for is that the content inside the box can still be scrolled.

**Comment by MikeChav** [comment] 2019-03-12 17:31
You seem to have gotten it to work, I don't see the error. Close the thread?

**Comment by fancyapps** [comment] 2019-03-15 07:32
Actually, there have been no recent changes related to this issue. Keep in mind that browsers have their own bugs and issues and they are (slowly) improving. So, I am closing this for now, if anyone encounters same issue, then, please, reopen or create new issue.

**Closed by fancyapps** 2019-03-15 07:32 UTC

**Comment by thibaudcolas** [comment] 2019-08-29 20:55
The same issue was reported on my website, also specifically on Android (OnePlus 6, Android 9, Chrome 74). I can reproduce the problem very easily, even on my laptop with the device emulation of the Chrome DevTools, and also on Browserstack (Galaxy S9, Android 8)

- It’s impossible to scroll content, because Fancybox treats any touch as a drag or slide
- It’s impossible to click anywhere inside, again for the same reason
