### ISSUE TITLE
How to change the Share button code?

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#1974] opened 2018-06-14 11:36 UTC
If I enable the Share button and click on that button, I see 3 possible share functions:

Facebook, Twitter and Pinterest

If I use the Facebook button, I can add somehing to my FB page, but the showed picture does not correspond with the picture I liked to Share.

I miss other Share functions, like to share the picture via email.

So my questions are:

1. Is it possible to add more buttons and code for extra share functions?
2. How can I replace standard share code, like the FB share code, to correct that code so that the correct image is displayed on my FB page?

**Comment by fancyapps** [comment] 2018-06-14 16:15
This partially duplicate of #1772

Share module is quite basic, check out https://github.com/fancyapps/fancybox/blob/master/src/js/share.js

If you wish, you can replace main template ( `$.fancybox.defaults.share.tpl` ) with your own. Or simply create your own share module based on the current one.

**Closed by fancyapps** 2018-06-14 16:15 UTC

**Comment by acwolff** [comment] 2018-10-25 07:16
Where can I fint the $.fancybox.defaults.share.tpl template?

**Comment by acwolff** [comment] 2018-10-25 08:40
I added my own Facebook share function  fbShareSlide() as follows

    share: {
      url: function(instance, item) {
        return (
          (!instance.currentHash && !(item.type === "inline" || item.type === "html") ? item.origSrc || item.src : false) || window.location
        );
      },
      tpl:
        '<div class="fancybox-share">' +
        "<h1>{{SHARE}}</h1>" +
        "<p>" +
        '<a class="fancybox-share__button fancybox-share__button--fb" href="javascript:fbShareSlide()">' +
        '<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><path d="m287 456v-299c0-21 6-35 35-35h38v-63c-7-1-29-3-55-3-54 0-91 33-91 94v306m143-254h-205v72h196" /></svg>' +
           "<span>Facebook</span>" +
    "</a>" +

bus this does not work, the program does not come in my function fbShareSlide(), see https://www.andrewolff.nl/FotoSerie/Wandelingen/sGravenland/

Any idea what I do wrongly?

**Comment by fancyapps** [comment] 2018-10-25 08:47
I guess this is caused by the fact that the script adds default click event to `.fancybox-share__button` elements , so, to overcome that, you either have to somehow unbind that or choose other css classname (or use that file as a template to create custom share module, as you can see, it is very simple).

**Comment by acwolff** [comment] 2018-10-25 09:02
Sorry, that is too difficult for me to understand!

The standard Pinterest share function is alo not correctly working, I get an error message for the image URL:
Parameter 'image_url' with value 'https:slides/2011%2010%2019_0000B-2.jpg' is not a valid URL.

The correct URL is https://www.andrewolff.nl/FotoSerie/Wandelingen/sGravenland/slides/2011%2010%2019_0000B-2.jpg

**Comment by fancyapps** [comment] 2018-10-25 10:47
I guess you need to use `encodeURIComponent` to properly encode your link.

**Comment by acwolff** [comment] 2018-10-25 11:12
?? what is so special on my link, is it correctly working at your site?
