### ISSUE TITLE
Desktop Zoom (not the same as other zoom bugs)

### ISSUE THREAD

**Issue by robhuska** [fancyapps/fancybox#1355] opened 2017-04-10 14:29 UTC
I am looking to disable the actual zoom feature on desktop, not the animation that happens when you initiate an instance of fancybox, but the zoom-ability that is there when an image is larger than the available space. It happens when you click the image when the magnify cursor is showing. I saw if I set touch to false it gets rid of the magnify cursor, but a click still allows it to zoom.  And on mobile if you zoom, you then cannot pan, so that is not going to work.

So is there anyway to get rid of the zoom-ability?

**Comment by fancyapps** [comment] 2017-04-11 07:14
Duplicate of #1175

In v.3.1 you will be able to control what happens on click / double click.

**Closed by fancyapps** 2017-04-11 07:14 UTC

**Comment by robhuska** [comment] 2017-04-11 14:10
Thanks! Any update on timeframe for v.3.1? BTW, this plugin is amazing.

**Comment by fancyapps** [comment] 2017-04-11 14:12
Thanks, I plan to finish this week. You can follow twitter for updates.
