### ISSUE TITLE
How to place title/caption right below the content?

### ISSUE THREAD

**Issue by stratboy** [fancyapps/fancybox#2288] opened 2019-06-18 10:15 UTC
Hi, I tried suggestions found on the web, like using data-fancybox-title attribute, but nothing works.

I would like to place the caption, or title, whatever, right below the image/video and not at the bottom of the window. Just like here:

http://jsfiddle.net/E4qxU/

It seems currently is not possible. At lease when showing a video (not tried when showing an image, but since markup is quite the same, I guess media type is not relevant here).

How to?

**Comment by fancyapps** [comment] 2019-06-18 14:41
Duplicate of #1200

**Closed by fancyapps** 2019-06-18 14:41 UTC

**Comment by stratboy** [comment] 2019-06-18 14:57
On #1200 there's not a real answer to my question. Anyway, I managed to solve it like this:

// js   

``` js
$('[data-fancybox]').fancybox({
  afterShow: function(fb, item){
    var content = fb.$refs.stage.find('.fancybox-content');
    content.append(fb.$refs.caption); // move caption
  }
});
```

// css

``` css
.fancybox-caption{
  bottom: -30px;
  background: none;
}
```

**Comment by stratboy** [comment] 2019-06-19 09:34
I'd really like you to add an option to instantiate the caption right below the image.

**Comment by fancyapps** [comment] 2019-06-19 18:53
But why? If image dimensions exceed available space dimensions (like in your link; like in 99% cases), then caption will be at the bottom anyway, And what if caption will contain more than couple of words and user views, for example, on ipad? Then image will become tiny.

**Comment by stratboy** [comment] 2019-06-19 19:44
First, it can be just design. If the client or the designer wants the caption below the image, I need to do it. And I guess I'm not alone here. Second, none of your use cases applies to my current project, so it could have been a little difficult to explain to my client why I cannot do it.
A lot of clients just have big screens... And I also think it should not be your responsibility to take care about how long are the captions the client writes, as long as you let him to choose between different layouts.

Apart from that, your work is fabulous.

**Comment by acwolff** [comment] 2019-06-20 07:05
FancyBox can handle long comments very well, some examples;
https://andrewolff.jalbum.net/ExtendedCommentDirectVisible_FB/
https://andrewolff.jalbum.net/ExtendedComment_FB/
https://andrewolff.jalbum.net/ExtendedCommentModal_FB/
https://andrewolff.jalbum.net/ExtendedCommentSidePanel/

**Comment by fancyapps** [comment] 2019-06-21 06:43
Lets assume that your images are small enough to fit inside view-port. Then the question is - where would caption be positioned while image is loading and what happens when image loads. Current design avoids ugly transition/content jumping and allows user to read caption while image is loading thus making staring at blank screen less painful. 

Well, if you have predefined image width/height then you could calculate final position of image and place caption accordingly, but, if you do not know final image dimensions, then you basically have two choices - hide caption while image is loading or move caption (with or without animation) below image after it completes loading (which is totally unnecessary and annoying, actually, both choices are annoying).

I think this is the main reason why the biggest web-pages use a similar layout (facebook, engadget, nationalgeographic, theguardian, etc, etc). 

Another points why default layout is better choice - caption always stays at the same place while navigating the gallery (gallery image might have different aspect ratios, therefore your captions might jump up/down) and you can have a place to place social icons, ads, etc

**Comment by stratboy** [comment] 2019-06-21 07:00
I don't think hiding the caption while loading is annoying, it's just what I already done. And that solves the issue. And anyway, It's not a so strange solution to have the caption below the image, it has already been done by many coders (including me: once upon a time I programmed and freely distributed a plugin for Mootools: Milkbox, essentially a Lightbox evolution, which was used by many many people).

Your points are all good, I personally wouldn't change anything. But my client and its designer do want that, and it's a perfectly normal design choice. And with the code above and some extra lines, I already done it. So I can guarantee: it's not dangerous, you can safely pass the line :)

**Comment by fancyapps** [comment] 2019-06-21 07:07
To be honest, I have already implemented this for v4 (completely different approach, because layout will be built using flexbox), but the TODO list soooo big, therefore I can not tell when it will be ready to be published.

**Comment by stratboy** [comment] 2019-06-21 07:16
The (other) good news is that your script is so good that it was flexible enough to already let me achieve what I needed. So no need for hurry. :)
