### ISSUE TITLE
html dir="rtl" Support - Use Absolute ltr direction

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [fancyapps/fancybox#1827] opened 2018-02-07 01:43 UTC
I Don't know why in the code i find "`direction: rtl;`" (So I don't create pull Req). 

## Where?
https://github.com/fancyapps/fancybox/blob/master/src/css/core.css

## What?
on RTL sites "dir=RTL" added to html tag (By `W3C `[recommendation](https://www.w3.org/International/questions/qa-html-dir))
The styles inside `core.css` override my RTL direction

## Before
![image](https://user-images.githubusercontent.com/16711871/35894744-e7ac600e-0bbc-11e8-8a6e-98b847d11e0a.png)

All styles are flip (LTR) + caption: "text-align: left" (But in RTL the text-align is right) + The close btn should be on left-side in RTL

## Solution "After"
Her 3-4 lines of code i added to solve this issue (or remove the direction from the core code):
https://codepen.io/ezra_siton/pen/oEzMBo

```

/* 1-2 -- FIX THE RTL PROBLEM */
html[dir="rtl"] .fancybox-stage {
  direction: inherit;
}
html[dir="rtl"] .fancybox-slide > * {
  text-align: initial;
}
/* 2-2 -- FIX Caption Decleration */
html[dir="rtl"] .fancybox-caption-wrap{
  direction: inherit;
}
/* 3-3 - FIX close button position */
html[dir="rtl"] .fancybox-close-small{
	left: 0;
	right: initial;
}




```

**Comment by fancyapps** [comment] 2018-02-13 09:28
Thanks! 

This is also (partly) duplicate of #1210

**Closed by fancyapps** 2018-02-13 09:28 UTC
