### ISSUE TITLE
FancyBox3 video in hidden <Div> on moble devices plays but has green tint

### ISSUE THREAD

**Issue by MicJarek** [fancyapps/fancybox#1858] opened 2018-02-26 00:11 UTC
Hi,

I'm using a `<Div>` container to play a .mp4 video using FancyBox3, and for the most part it works fine on regular PC based browsers like Firefox, IE, and Edge (NOTE: in Opera or Safari the sound plays, but the screen is black - this is a separate issue).

When I try and play the same video in a browser on a mobile device (i.e. cell phone), the sound plays fine, but there is this green tint over the video that makes it next to impossible to see. Note: I'm also using the latest jquery-3.2.1.min.js so hopefully that's not an issue.

Here is a page to see what I mean (http://www.beatonmyheart.com/myheart/Procedure.aspx) 
And code I used is pretty basic:

    <a data-fancybox="gallery" data-src="#video1" data-width="480" data-height="384" data-caption="Caption goes here..." >
        <img src="data/video/Video1 - Thumb.png" align="left" alt="" ></a>
        <div hidden id="video1" style="margin: 1px; padding: 1px; background-color: #000000;">
              <video width="480" height="384" controls ><source src="data/video/Video1.mp4" type="video/mp4">Your browser does not support HTML5 video.</video>
        </div>

Has anyone else tried to display an .mp4 video via FancyBox3 using a hidden `<Div>` and is having the same problem? Any feedback/suggestions would be greatly appreciated.

Tks... :)

**Comment by fancyapps** [comment] 2018-02-26 08:56
Duplicate of #1857

**Closed by fancyapps** 2018-02-26 08:56 UTC
