### ISSUE TITLE
FancyBox generates unwanted click events

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2022] opened 2018-07-31 10:17 UTC
[This album](https://andrewolff.jalbum.net/Vecht_SaharaN_FB_ShowBug/) contains next code:
    
     $('[data-fancybox="S"]').fancybox({
    	onInit : function() {
    		FancyBoxIsOpen = true;
    		FancyBoxInstance = $.fancybox.getInstance();
        },
        beforeShow : function() {
    	    	slide_index= this.index;
    		slideType = this.contentType;
    		$(".fancybox-button--expand").hide();
    		expandShown = false;
    		if (typeof(pano) !== 'undefined') {
    			if (pano[slide_index] > 0) { $(".fancybox-button--expand").show();  expandShown = true; }
    		}
        },
        	afterClose : function() {
    		FancyBoxIsOpen = false;
    		if (skipIndexPage && !hideCloseButton) {closeAlbum();}	 
        },
        clickContent:  function() {
    		beep(); 
    		if (enableSlideShow) {
    			FancyBoxInstance.SlideShow.toggle();
    			return false;
    		} else {
    			return "next";
    		}
    },
      mobile : {
        clickContent :  function() {
    		beep();
    		if (enableSlideShow) {
    			FancyBoxInstance.SlideShow.toggle();
    			return false;
    		} else {
    			return "next";
    		}
    	}
      },
    protect: true, // protect images from downloading by right-click
        slideShow: {
            autoStart: false,
            speed: viewtime
        },
        transitionEffect: transeffect,
        transitionDuration: transtime,
        buttons : [
        'expand',
        'zoom',
        'slideShow',
        'thumbs',
     'close'
      ]
    });

This code shows an extra expansion button in case of an panoramic picture and clicking in the images starts /stop the slide show.
However that is not correctly working because unwanted click events are generated if an expansion button is showed and in case the window is resized.

To prove this I added a beep() function which produces a sound if the click event is triggered.

To see the problem [click here](https://andrewolff.jalbum.net/Vecht_SaharaN_FB_ShowBug/)  to open the album. Click next on a thumbnail to open fancyBox and resize the window, you will hear the sound.
You hear the sound also twice if an expansion button shows up in the tool-bar.

How can I prevent this unwanted click events?

**Comment by fancyapps** [comment] 2018-08-02 18:37
Hmm, true. Thanks for reporting.

**Comment by fancyapps** [comment] 2018-08-30 11:50
Duplicate of #2048

**Closed by fancyapps** 2018-08-30 11:50 UTC
