### ISSUE TITLE
bower.json duplicate main file

### ISSUE THREAD

**Issue by Horttcore** [fancyapps/fancyBox#1078] opened 2015-11-27 12:51 UTC
`{
    "name": "fancybox",
    "main": [
        "source/jquery.fancybox.js",
        …
        "source/jquery.fancybox.pack.js"
    ],
    …
}`

I think it would be better if only the packed version would be in the main object and not both.

**Comment by Traksewt** [comment] 2016-01-07 06:23
Actually, the bower spec says to not include minified files in the main. So include the unpacked version instead.
https://github.com/bower/spec/blob/master/json.md
"Do not include minified files."

**Comment by fancyapps** [comment] 2017-02-28 12:38
Duplicate of #820

**Closed by fancyapps** 2017-02-28 12:38 UTC
