### ISSUE TITLE
fancybox 3 - trying to animate slides but prevent animation on open/close

### ISSUE THREAD

**Issue by dsheyp** [fancyapps/fancybox#1256] opened 2017-03-04 22:05 UTC
hi

i'm trying to prevent any animation on open/close of fancybox and at the same time keep the animation when changing slides. the closest i can get is by doing something like that:
```
var $instance = $.fancybox.open($('.fancybox'),{
  speed : 0,
  afterLoad : function(instance) {
  	this.opts.speed = 330;
  	instance.current.opts.speed = 0;
  },
  .......
});
```
my solution doesn't work perfectly, some slides do still show with `speed = 0` . is there a better way to achieve what i want?

thanks
dsheyp

**Comment by fancyapps** [comment] 2017-03-06 08:53
Hi, sorry, current version lacks options for disabling open/close animations.

There are a few API changes planned for v3.1, including ones related to animations.

**Comment by fancyapps** [comment] 2017-03-06 10:10
Duplicate of #1175

**Closed by fancyapps** 2017-03-06 10:10 UTC
