### ISSUE TITLE
ios devices focus input[text] incorrect cursor position

### ISSUE THREAD

**Issue by AJIEKCEU** [fancyapps/fancybox#1785] opened 2017-12-22 06:46 UTC
when open fancybox and focus input[text] or other field, cursor position incorrect. This problem in apple devices. 
![image](https://user-images.githubusercontent.com/3834281/34288211-ea0dcfa2-e6fc-11e7-852d-6e3fb375f7f6.png)

[https://burger-king.by/](url)

![image](https://user-images.githubusercontent.com/3834281/34288186-bc0426d8-e6fc-11e7-8e88-22642cf8583f.png)
![image](https://user-images.githubusercontent.com/3834281/34288194-c6fd8124-e6fc-11e7-9fed-f96fa04a0be2.png)

**Comment by fancyapps** [comment] 2017-12-22 09:01
Duplicate of #1785

This is a well known iOS bug, see https://hackernoon.com/how-to-fix-the-ios-11-input-element-in-fixed-modals-bug-aaf66c7ba3f8 and there is currently no perfectly working workaround for this. This bug is reported here - https://bugs.webkit.org/show_bug.cgi?id=176896

**Closed by fancyapps** 2017-12-22 09:01 UTC
