### ISSUE TITLE
(Fancy box3) Thumbnail glitch on Android native browser in Android 4.2.2. 

### ISSUE THREAD

**Issue by sohrabzia** [fancyapps/fancybox#1344] opened 2017-04-05 13:46 UTC
Hi. I am having issue with thumbnail on galaxy tab 3. When i tap thumbnail icon, thumbnails appears and dissappear  immediately. 
I'm just simply markup with 3 images. I guess it is happening with outdated browsers. Is there any workaround? Thanks.

**Comment by fancyapps** [comment] 2017-04-05 17:59
Hi. 

It would be great if you could debug code to check what is causing this issue, because I am testing on Nexus tablet and it works fine. What browser and version are you using?

**Comment by sohrabzia** [comment] 2017-04-06 12:17
Thanks for awesome plugin 👍 
It is happening on android jellybeans 4.2.2, galaxy tab 3 on native browser. it is old browser I am not able to debug it.

**Comment by fancyapps** [comment] 2017-06-08 13:06
Hi,

Sorry, I'm closing this, because I could not figure out what could be the cause. There is a simple click event attached to the button and it simply toggles the list.

**Closed by fancyapps** 2017-06-08 13:06 UTC
