### ISSUE TITLE
Updating Window Location for Ajax Links

### ISSUE THREAD

**Issue by Ne-Ne** [fancyapps/fancyBox#869] opened 2014-05-22 12:19 UTC
I am using the latest version of fancybox, however I cannot seem to get the window location to update based on ajax call to the same origin.

Can someone test this, as It would be helpful to my websites visitors. The support docs does not provide an example, but I think this would be a great use case.

Especially for dynamic content which is not related to the current page topic.

**Comment by fancyapps** [comment] 2017-02-28 11:46
Possibly duplicate of #383

**Closed by fancyapps** 2017-02-28 11:46 UTC
