### ISSUE TITLE
On click next image and how to disable click to zoom

### ISSUE THREAD

**Issue by davemccoy** [fancyapps/fancybox#1330] opened 2017-03-29 11:53 UTC
Hello, i need to disable drag image to next image, only click for display next image and disable zoom on ckick

**Comment by fancyapps** [comment] 2017-03-29 11:55
Options to customize this will be included in v3.1. 
The work is in progress, probably will be ready next week.

**Comment by fancyapps** [comment] 2017-03-29 11:55
Duplicate of #1175

**Closed by fancyapps** 2017-03-29 11:55 UTC
