### ISSUE TITLE
Inconsistent download link with srcset

### ISSUE THREAD

**Issue by stanvass** [fancyapps/fancybox#1923] opened 2018-04-24 23:03 UTC
Let's say I have code like this:

```
<a href="/full/bar.jpg" target="_blank" data-fancybox="gallery146" data-srcset="/big/bar.jpg 1920w, /small/bar.jpg 1280w">...</a>
```

When I open a photo, I see a photo from the srcset, while the download button points to /full/bar.jpg. That's the correct behavior. Unfortunately when I switch to other photos, the download button starts pointing to the srcset image I'm viewing.

So basically:

1. The link on first opened image is correct on downloads (full image from the href).
2. The link on subsequent navigated-to images is not correct (the current srcset image).

**Comment by fancyapps** [comment] 2018-05-17 12:53
This is duplicate of multiple closed issues.

**Closed by fancyapps** 2018-05-17 12:53 UTC

**Comment by stanvass** [comment] 2018-06-15 20:38
@fancyapps At the time I reported it it was still in the official release, so I hope you fixed it. I had to patch it on my own locally.
