### ISSUE TITLE
Is Version 4 still in development?

### ISSUE THREAD

**Issue by Nimrod-666** [fancyapps/fancybox#2581] opened 2021-04-16 14:47 UTC
Hi, i'm waiting for fancybox version 4 to remove jquery from my dependencies, but now i've seen that there was no commit into the master-branch for more than a year and i like to ask if the project is still active and if you guys can estimate when version 4 will be released? Would be sad if not, i think it's a great project!

**Comment by fancyapps** [comment] 2021-04-19 07:35
Hi,

Thanks for your interest, it is coming. The code is actually ready, I am right now working on the homepage, so, please, be patient :)

Duplicate of #1346

**Closed by fancyapps** 2021-04-19 07:35 UTC

**Comment by Whateverinc** [comment] 2021-04-29 03:47
Can't wait. Feels like Christmas is coming soon!

**Comment by mjcampagna** [comment] 2021-05-17 02:18
@fancyapps Really excited to lay hands on the new version when it's ready, Jānis. What's the best way to be informed of the release when it happens?
