### ISSUE TITLE
Can't swipe horizontally when viewport height less than fancybox content height

### ISSUE THREAD

**Issue by tsymbal** [fancyapps/fancybox#1875] opened 2018-03-12 08:08 UTC
Hi! 
Fancybox 3.1.25 (also tried 3.2.10)
If "inline" or "ajax" content has a higher actual height than the viewport, then the horizontal scroll stops working. If the content is placed in the viewport, then everything is ok. 
Example:
https://share.vidyard.com/watch/6nCiw48AWTtMCAzej5HTYP
Problem is relevant for both PC and mobile.

Maybe this is not a bug. But how can i resolve it?

**Comment by fancyapps** [comment] 2018-03-12 08:16
Duplicate of #1528

**Closed by fancyapps** 2018-03-12 08:16 UTC
