### ISSUE TITLE
scss version of styles

### ISSUE THREAD

**Issue by stratboy** [fancyapps/fancybox#1845] opened 2018-02-16 16:23 UTC
Hi! It would be great if you also added scss version to the styles!

Thank you for your code, regards

**Comment by fancyapps** [comment] 2018-02-26 10:22
Hi. Maybe someday.

Also, not sure witch is better - SASS or SCSS. And CSS variables have pretty good browser support, too (except IE11) - https://caniuse.com/#feat=css-variables

Duplicate of #1372

**Closed by fancyapps** 2018-02-26 10:22 UTC
