### ISSUE TITLE
Full width zoom for very tall images

### ISSUE THREAD

**Issue by tsarevpp** [fancyapps/fancybox#1943] opened 2018-05-23 14:29 UTC
Hello, I want to implement fancybox with my admin system and I have some documents (mostly about 2 pages) that are stacked and saved as tall images. I want to display them with fancybox and to be able to zoom them to full width. There isn't an option to do this currently. The zoom for me shows 3/4 of the image width when i zoom in. Is there a way to do this or maybe this could be a future in the next release? :) 
Thanks!

**Comment by fancyapps** [comment] 2018-05-28 11:01
Duplicate of #1343

**Closed by fancyapps** 2018-05-28 11:01 UTC

**Comment by tsarevpp** [comment] 2018-05-28 11:04
@fancyapps Did you read the whole post? The image is not properly zoomed.

**Comment by fancyapps** [comment] 2018-05-28 11:05
Hmm, sorry, could you provide some demo?
