### ISSUE TITLE
Using data-src as the #hash URL instead of data-fancybox

### ISSUE THREAD

**Issue by bountydigital** [fancyapps/fancybox#1891] opened 2018-03-23 23:20 UTC
Hi! Thanks for the amazing plugin! It just gets better and better. 

Just a quickie, I was wondering if possible to have a custom value as the #hash URL. I have a group of inline content with [data-fancybox="nature"] and currently the default is:
www.website.com/#nature-1
www.website.com/#nature-2
www.website.com/#nature-3

However as the data-src varies to call each specific hidden content/DIV i was wondering if it was possible to change the URL to be:
www.website.com/#tree
www.website.com/#flower
www.website.com/#mountain

So it will be possible to direct link to each specific DIV in a more descriptive way?

**Comment by fancyapps** [comment] 2018-04-03 17:24
Hi,

Thanks for your kind words.

This seems to be duplicate of #1407

**Closed by fancyapps** 2018-04-03 17:24 UTC
