### ISSUE TITLE
Error while compilling css

### ISSUE THREAD

**Issue by Safe-Mode** [fancyapps/fancybox#2156] opened 2018-12-17 21:31 UTC
**To Reproduce**
import css from node_modules folder

**Expected behavior**
Just get some default styles provided by fancybox

**Additional context**
But I've got this error. 

http://prntscr.com/lw8h5r

It was the first time. Everything seems working before

**Comment by fancyapps** [comment] 2018-12-18 06:33
Duplicate of #2153 - This is a saas bug

**Closed by fancyapps** 2018-12-18 06:33 UTC
