### ISSUE TITLE
Create a tag with bower.json 

### ISSUE THREAD

**Issue by ianllewellyn** [fancyapps/fancyBox#849] opened 2014-04-10 10:58 UTC
bower.json has been added to master but the latest tag (v2.1.5) doesn't include the file. Can we get a new patch tag (v2.1.6) that includes bower.json with main property so we can use automatic builders?

**Comment by fancyapps** [comment] 2017-02-28 12:39
Duplicate of #820

**Closed by fancyapps** 2017-02-28 12:39 UTC
