### ISSUE TITLE
Combine slider and fancyBox - Small Q

### ISSUE THREAD

**Issue by Siton-Systems** [fancyapps/fancybox#1602] opened 2017-08-29 20:13 UTC
https://codepen.io/fancyapps/pen/eWVyVg

How can i move the **current slide** depend on the current **zoom image**? 

**Example:** 

- I click on **image1-thumbnail** 
- then swipe to image2...3...4..5...
- Now when i **close** **image5** i want to see in the **slider** **image5-thumbnail** and not **image1-thumbnail**) (BETTER UI)

Reference for this UI (see the image slider)
http://www.booking.com/Share-0B9PdA

Thanks for any advice.

**Comment by fancyapps** [comment] 2017-08-31 13:58
Hi,

I can give you the idea how this could be done, but, unfortunately, I have no idea how to make it work perfectly. Maybe you can ask someone who has better knowledge about this slider. 

So, the idea is simple - before closing fancyBox, check what current image is and move slider to corresponding position. And the problem is - how to determine this position correctly. It works fine only if you disable looping and enable `centeredSlides`. 

The code could look like this (https://codepen.io/anon/pen/QMzZmG) - 

```JS
var mySwiper = new Swiper ('.swiper-container', {
  // Optional parameters
  direction : 'horizontal',
  loop : false,
  slidesPerView : 3,
  centeredSlides: true
});     

$().fancybox({
  selector : '[data-fancybox="images"]',
  thumbs   : false,
  hash     : false,
  animationEffect : "fade",
  beforeClose : function(instance) {
    
    // This is index of current fancyBox slide
    console.info( instance.currIndex  );
    
    // Update position of the slider
    mySwiper.slideTo( instance.currIndex, 0 );
    
  }
});


```

**Closed by fancyapps** 2017-08-31 13:58 UTC

**Comment by Siton-Systems** [comment] 2017-09-01 02:29
WOW :) thanks. Works great.
