### ISSUE TITLE
Enable the Caption to "hug" the bottom of the image

### ISSUE THREAD

**Issue by rouviere** [fancyapps/fancybox#1846] opened 2018-02-16 20:23 UTC
In one form or other this has been mentioned in multiple requests and comments, but I would like to request it again. The caption needs to be able to hug the bottom of the photo. Defaulting the image to the bottom of the window may work for many smaller devices, but on large monitors or even larger iPads in vertical position the caption can be a long way from the image and not seen.

Yes, it is possible to set the margin to push up the caption, but this can also be problematic since in certain scenarios it could overlap the image. By making the caption hug the bottom of the image it can respond with the image size depending on the device or the users resizing of the window.

Thanks for the great product. This will serve to enhance it greatly.

**Comment by fancyapps** [comment] 2018-04-09 10:07
Thanks for your kind words.

I just noticed that this is duplicate of #1846

At this point, I am not sure on what feature to focus. This seems to be quite popular, so I`ll take a look.

**Closed by fancyapps** 2018-04-09 10:07 UTC
Labels: Feature request
