### ISSUE TITLE
Sharing the individual image open graph / twitter

### ISSUE THREAD

**Issue by carasmo** [fancyapps/fancybox#1826] opened 2018-02-06 18:28 UTC
I am looking at the demo https://fancyapps.com/fancybox/3/ and when I click the share icon, only the first image is showing in Facebook. In Pinterest it can't find an image. I haven't checked the Twitter card. I would assume that the image should be the image you're sharing, the one your are looking at in the lightbox,  and the caption is the text in any of these networks. 

Is there some setting that I'm not setting up correctly?

**Comment by fancyapps** [comment] 2018-02-07 11:49
Duplicate of #1772

**Closed by fancyapps** 2018-02-07 11:49 UTC
