### ISSUE TITLE
Open Video Tag in FancyBox 3 in IE browser Error

### ISSUE THREAD

**Issue by Nageshwar** [fancyapps/fancybox#1672] opened 2017-10-10 07:14 UTC
Hello Team,

I am getting this issue in opening the local video file using Fancybox 3 , which is getting an error and first tries to download before playing the video and once it is downloaded then it is been playing in local player rather inside FancyBox.

![screenshot_24](https://user-images.githubusercontent.com/3288042/31373699-b49e0a26-adb8-11e7-8f20-92ba2cf79308.png)

Please find the screenshot to understand, Still need any clarification you can always reply but please provide me the correct way to insert video and make it working.

Thanks for your early feedback
Nageshwar Jha

**Comment by fancyapps** [comment] 2017-10-10 07:16
Hi, This is duplicate of #1671

**Closed by fancyapps** 2017-10-10 07:16 UTC
