### ISSUE TITLE
Files with space in name aren't shown in thumbnails

### ISSUE THREAD

**Issue by Arsavin** [fancyapps/fancybox#2480] opened 2020-06-23 13:54 UTC
I have this html:

```
<a href="http://example.com/6/value/ro/100x100/Do it right.jpg" data-thumb="http://example.com/6/value/ro/100x100/Do it right.jpg" data-fancybox="files.6.gallery.new">
    <i class="fa fa-search-plus"></i>
</a>
```

If clicking the link, image is shown, but in thumbnails is not. That is because file has spaces.

**Comment by fancyapps** [comment] 2020-06-30 09:27
Duplicate of #2480

**Closed by fancyapps** 2020-06-30 09:27 UTC
