### ISSUE TITLE
Fancybox breaks "back" button

### ISSUE THREAD

**Issue by ipsod** [fancyapps/fancybox#1321] opened 2017-03-24 16:22 UTC
In Fancybox 3.0, after opening and closing a gallery, the "back" page no longer goes to the previous page, but re-opens the gallery.  If multiple photos were viewed in the gallery, it layers the break-age, and it can take quite a few clicks of the "back" button to ever get to the previous page.

Is there any way to fix this?

**Comment by fancyapps** [comment] 2017-03-24 16:24
Duplicate of #1313

**Closed by fancyapps** 2017-03-24 16:24 UTC
