### ISSUE TITLE
Function on closeClickOutside?

### ISSUE THREAD

**Issue by seabasss** [fancyapps/fancybox#1353] opened 2017-04-08 02:54 UTC
Is it possible to add a function to closeClickOutside?

I have a script that looks if something has changed, so the user don't close the fancybox unintentionally and loose all the data. Something like this?

```
var $form = $('#form'),
origForm = $form.serialize();
$('.fancybox-container').attr('tabindex', -1).focus();
$('.fancybox-container').on(closeClickOutside, function() { // you get the point...
	var $current_fancybox = $.fancybox.getInstance();
	if( $form.serialize() !== origForm )
	{
		$('.fancybox-container').fancyConfirm({
			title    : 'Are you sure?',
			message  : 'You have unsaved changes',
			decline  : 'cancel',
			confirm  : 'Close',
			callback : function (value) {
				if (value) {
					$current_fancybox.close();
				}
			}
		});
	} else {
		$current_fancybox.close();
	}
});
```

**Comment by GeorgeRT** [comment] 2017-04-11 02:04
Why not disable closeClickOutside?

**Comment by seabasss** [comment] 2017-04-11 02:14
Yes, but I'd need a function to replace that then. Any ideas?

When the user clicks outside the fancybox (in the overlay) I want the confirm window to pop up before closing out of the fancybox.

**Comment by fancyapps** [comment] 2017-04-11 06:31
This will be customizable in v3.1. 

Duplicate of #1175

**Closed by fancyapps** 2017-04-11 06:31 UTC
