### ISSUE TITLE
TypeScript import

### ISSUE THREAD

**Issue by djereg** [fancyapps/fancybox#1340] opened 2017-04-03 23:00 UTC
The TypeScript import or Nodejs require() support would be a good feature.

For example https://github.com/kombai/freewall

**Comment by djereg** [comment] 2017-04-10 18:51
Ahh! Found how to require() the plugin in Node js, but how to import it in TypeScript (Angular 2)?

**Comment by fancyapps** [comment] 2017-06-08 13:09
Probably duplicate of #1376

**Closed by fancyapps** 2017-06-08 13:09 UTC
